SELECT 'ORIGEN_TABLA_FUNCIONARIOS', A.NUMERO 
FROM FUNCIONARIOS A INNER JOIN
AFILIADOS B 
ON A.NUMERO = B.NUMERO
UNION
SELECT 'ORIGEN_TABLA_ESTADO', D.NUMERO 
FROM ESTADO C 
INNER JOIN FUNCIONARIOS D 
ON C. NUMERO = D. NUMERO;