INSERT into AFILIADOS (NUMERO, NOMBRE)
  VALUES
  ('430','CAMILO PULGARIN'),
  ('65','ALEX TORRES'),
  ('9301','ALEJANDRA ALVARADO'),
('739301','MAURICIO SANCHEZ'),
('803151','JOSE SIERRA');
  
INSERT into AREA_ENCARGADA (PRESTACIONES_ECONOMICAS, CARTERA, RECAUDO, AFILIACIONES)
  VALUES
  ('CLAUDIA SARMIENTO','JUAN ACUNA','PATRICIA CANO', 'FELIPE RUIZ' ),
  ('DIANA MELO','CAROLINA RUIZ','JOAQUIN PERDOMO', 'MIGUEL AREVALO' ),
  ('CAMILA LUGO','INGRID VELANDIA','SEBASTIAN MORENO', 'LUISA LOPEZ' ),
('FERNANDA RUIZ','LILIANA COMBITTA','FEDERICO PEREZ', 'PABLO TORRES' );


INSERT into SOLICITUD (solicitante, causal, categorizacion)
  VALUES
  ('CLAUDIA SARMIENTO','PRESTACION DEL SERVICIO','PRIORITARIA'),
  ('DIANA MELO','NO REGISTRA APORTES','NORMAL'),
  ('CAMILA LUGO','SIN AFILIACION','NORMAL'),
('FERNANDA RUIZ','SOLICITUD DEVOLUCION DE APORTES','PRIORITARIA');

INSERT into ESTADO (DESCRIPCION_ESTADO)
  VALUES
  ('INICIO'),
  ('EN PROCESO'),
  ('FINALIZADO');
